// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type AddAuthPwReq struct {
	AuthPw string `json:"authPw"`
}

type AddAuthPwResp struct {
}

type AddDownloadLinkReq struct {
	DownloadLink string `json:"downloadLink"`
}

type AuthData struct {
	AuthStatus string `json:"authStatus"` //认证状态
	ExpireAt   string `json:"expireAt"`   //过期时间
}

type DownFileInfo struct {
	Url     string `json:"url"`
	AddTime string `json:"addTime"`
}

type NilResp struct {
	Success bool   `json:"success"`
	Message string `json:"message,omitempty"`
}

type ServerInfoReq struct {
}

type ServerInfoResp struct {
	DownFileInfoList []DownFileInfo `json:"downFileInfoList"`
	AuthData         AuthData       `json:"authData"`
	Mode             int64          `json:"mode"` //默认只下载视频 mode为1是下载全部
}

type SetDownloadModeReq struct {
	Mode int64 `json:"mode"` //默认只下载视频 mode为1是下载全部
}

type StartReNameReq struct {
	Mode          int64  `json:"mode"`          // 重命名模式 0全量重命名(递归所有文件夹) 1增量重命名(只处理指定文件夹)
	FolderID      string `json:"folder_id"`     // 起始文件夹ID，如果为空则从根目录开始
	FilePattern   string `json:"file_pattern"`  // 文件模式正则表达式，默认为(?i)[a-z]+-\d+
	DeleteOthers  bool   `json:"delete_others"` // 是否删除其他文件
	RenameToMatch bool   `json:"rename_match"`  // 是否将文件重命名为匹配项
}
