// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	Download "115Quick_server/internal/handler/Download"
	"115Quick_server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 重命名
				Method:  http.MethodPost,
				Path:    "/api/StartReName",
				Handler: Download.StartReNameHandler(serverCtx),
			},
			{
				// 添加认证密钥
				Method:  http.MethodPost,
				Path:    "/api/addAuthPw",
				Handler: Download.AddAuthPwHandler(serverCtx),
			},
			{
				// 添加下载链接
				Method:  http.MethodPost,
				Path:    "/api/addDownloadLink",
				Handler: Download.AddDownloadLinkHandler(serverCtx),
			},
			{
				// 获取云下载任务列表
				Method:  http.MethodGet,
				Path:    "/api/getCloudTasks",
				Handler: Download.GetCloudTasksHandler(serverCtx),
			},
			{
				// 获取下载进度
				Method:  http.MethodGet,
				Path:    "/api/getDownloadProgress",
				Handler: Download.GetDownloadProgressHandler(serverCtx),
			},
			{
				// 获取服务器信息
				Method:  http.MethodGet,
				Path:    "/api/getServerInfo",
				Handler: Download.GetServerInfoHandler(serverCtx),
			},
			{
				// 获取SMB配置
				Method:  http.MethodGet,
				Path:    "/api/getSMBConfig",
				Handler: Download.GetSMBConfigHandler(serverCtx),
			},
			{
				// 获取任务历史
				Method:  http.MethodGet,
				Path:    "/api/getTaskHistory",
				Handler: Download.GetTaskHistoryHandler(serverCtx),
			},
			{
				// 获取Token状态
				Method:  http.MethodGet,
				Path:    "/api/getTokenStatus",
				Handler: Download.GetTokenStatusHandler(serverCtx),
			},
			{
				// 手动刷新任务列表
				Method:  http.MethodPost,
				Path:    "/api/refreshTasks",
				Handler: Download.RefreshTasksHandler(serverCtx),
			},
			{
				// 删除待下载任务
				Method:  http.MethodPost,
				Path:    "/api/removeDownloadTask",
				Handler: Download.RemoveDownloadTaskHandler(serverCtx),
			},
			{
				// 设置下载模式
				Method:  http.MethodPost,
				Path:    "/api/setDownloadMode",
				Handler: Download.SetDownloadModeHandler(serverCtx),
			},
			{
				// 设置SMB配置
				Method:  http.MethodPost,
				Path:    "/api/setSMBConfig",
				Handler: Download.SetSMBConfigHandler(serverCtx),
			},
			{
				// 设置115 Token
				Method:  http.MethodPost,
				Path:    "/api/setToken",
				Handler: Download.SetTokenHandler(serverCtx),
			},
			{
				// 测试SMB连接
				Method:  http.MethodPost,
				Path:    "/api/testSMBConnection",
				Handler: Download.TestSMBConnectionHandler(serverCtx),
			},
			{
				// 获取服务器日志
				Method:  http.MethodGet,
				Path:    "/api/getServerLogs",
				Handler: Download.GetServerLogsHandler(serverCtx),
			},
			{
				// 获取云文件列表
				Method:  http.MethodGet,
				Path:    "/api/getCloudFiles",
				Handler: Download.GetCloudFilesHandler(serverCtx),
			},
			{
				// 创建文件夹
				Method:  http.MethodPost,
				Path:    "/api/createFolder",
				Handler: Download.CreateFolderHandler(serverCtx),
			},
			{
				// 删除文件
				Method:  http.MethodPost,
				Path:    "/api/deleteFile",
				Handler: Download.DeleteFileHandler(serverCtx),
			},
			{
				// 重命名文件
				Method:  http.MethodPost,
				Path:    "/api/renameFile",
				Handler: Download.RenameFileHandler(serverCtx),
			},
			{
				// 移动文件
				Method:  http.MethodPost,
				Path:    "/api/moveFile",
				Handler: Download.MoveFileHandler(serverCtx),
			},
			{
				// 设置默认下载目录
				Method:  http.MethodPost,
				Path:    "/api/setDefaultDownloadDir",
				Handler: Download.SetDefaultDownloadDirHandler(serverCtx),
			},
			{
				// 获取默认下载目录
				Method:  http.MethodGet,
				Path:    "/api/getDefaultDownloadDir",
				Handler: Download.GetDefaultDownloadDirHandler(serverCtx),
			},
			{
				// 浏览SMB文件
				Method:  http.MethodGet,
				Path:    "/api/smb/browse",
				Handler: Download.SMBBrowseHandler(serverCtx),
			},
			{
				// 从SMB下载文件
				Method:  http.MethodPost,
				Path:    "/api/smb/download",
				Handler: Download.SMBDownloadHandler(serverCtx),
			},
			{
				// 清空任务历史
				Method:  http.MethodPost,
				Path:    "/api/clearTaskHistory",
				Handler: Download.ClearTaskHistoryHandler(serverCtx),
			},
			{
				// 清空已完成任务
				Method:  http.MethodPost,
				Path:    "/api/clearCompletedTasks",
				Handler: Download.ClearCompletedTasksHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/Download"),
	)
}
