// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	Download "115Quick_server/internal/handler/Download"
	"115Quick_server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 重命名
				Method:  http.MethodPost,
				Path:    "/api/StartReName",
				Handler: Download.StartReNameHandler(serverCtx),
			},
			{
				// 添加认证密钥
				Method:  http.MethodPost,
				Path:    "/api/addAuthPw",
				Handler: Download.AddAuthPwHandler(serverCtx),
			},
			{
				// 添加下载链接
				Method:  http.MethodPost,
				Path:    "/api/addDownloadLink",
				Handler: Download.AddDownloadLinkHandler(serverCtx),
			},
			{
				// 获取服务器信息
				Method:  http.MethodGet,
				Path:    "/api/getServerInfo",
				Handler: Download.GetServerInfoHandler(serverCtx),
			},
			{
				// 设置下载模式
				Method:  http.MethodPost,
				Path:    "/api/setDownloadMode",
				Handler: Download.SetDownloadModeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/Download"),
	)
}
