// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type AddAuthPwReq struct {
	AuthPw string `json:"authPw"`
}

type AddAuthPwResp struct {
}

type AddDownloadLinkReq struct {
	DownloadLink string `json:"downloadLink"`
}

type AuthData struct {
	AuthStatus string `json:"authStatus"` //认证状态
	ExpireAt   string `json:"expireAt"`   //过期时间
}

type CloudTaskItem struct {
	InfoHash     string  `json:"infoHash"`
	Name         string  `json:"name"`
	Size         int64   `json:"size"`
	Status       int     `json:"status"` // -1=失败 0=分配中 1=下载中 2=完成
	PercentDone  float64 `json:"percentDone"`
	RateDownload int     `json:"rateDownload"` // bytes/s
	AddTime      string  `json:"addTime"`
	URL          string  `json:"url"`
}

type CloudTasksReq struct {
}

type CloudTasksResp struct {
	Tasks []CloudTaskItem `json:"tasks"`
	Count int             `json:"count"`
}

type DownFileInfo struct {
	Url     string `json:"url"`
	AddTime string `json:"addTime"`
}

type DownloadProgressItem struct {
	FileName   string  `json:"fileName"`
	FileSize   int64   `json:"fileSize"`
	Downloaded int64   `json:"downloaded"`
	Speed      float64 `json:"speed"`   // MB/s
	Percent    float64 `json:"percent"` // 0-100
	StartTime  string  `json:"startTime"`
}

type DownloadProgressReq struct {
}

type DownloadProgressResp struct {
	Downloads []DownloadProgressItem `json:"downloads"`
}

type NilResp struct {
	Success bool   `json:"success"`
	Message string `json:"message,omitempty"`
}

type RefreshTasksReq struct {
}

type RemoveDownloadTaskReq struct {
	URL string `json:"url"`
}

type ServerInfoReq struct {
}

type VersionInfo struct {
	Version       string `json:"version"`
	GitCommit     string `json:"gitCommit"`
	BuildTime     string `json:"buildTime"`
	LatestVersion string `json:"latestVersion"`
	UpdateURL     string `json:"updateUrl"`
	HasUpdate     bool   `json:"hasUpdate"`
}

type ServerInfoResp struct {
	DownFileInfoList []DownFileInfo `json:"downFileInfoList"`
	AuthData         AuthData       `json:"authData"`
	Mode             int64          `json:"mode"` //默认只下载视频 mode为1是下载全部
	Version          VersionInfo    `json:"version"`
}

type SetDownloadModeReq struct {
	Mode int64 `json:"mode"` //默认只下载视频 mode为1是下载全部
}

type SetTokenReq struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type StartReNameReq struct {
	Mode          int64  `json:"mode"`                   //重命名模式 0全量重命名 1增量重命名
	FolderID      string `json:"folder_id,optional"`     // 起始文件夹ID，如果为空则从根目录开始
	FilePattern   string `json:"file_pattern,optional"`  // 文件模式正则表达式，默认为(?i)[a-z]+-\d+
	DeleteOthers  bool   `json:"delete_others,optional"` // 是否删除其他文件
	RenameToMatch bool   `json:"rename_match,optional"`  // 是否将文件重命名为匹配项
}

type TaskHistoryItem struct {
	ID           int64   `json:"id"`
	URL          string  `json:"url"`
	Name         string  `json:"name"`
	Size         int64   `json:"size"`
	Status       int     `json:"status"` // 0=等待 1=下载中 2=完成 3=失败
	Progress     float64 `json:"progress"`
	ErrorMsg     string  `json:"errorMsg"`
	AddTime      string  `json:"addTime"`
	CompleteTime string  `json:"completeTime"`
}

type TaskHistoryReq struct {
	Page     int `json:"page,optional,default=1"`
	PageSize int `json:"pageSize,optional,default=20"`
}

type TaskHistoryResp struct {
	Items    []TaskHistoryItem `json:"items"`
	Total    int               `json:"total"`
	Page     int               `json:"page"`
	PageSize int               `json:"pageSize"`
}

type TokenStatusReq struct {
}

type TokenStatusResp struct {
	Configured bool   `json:"configured"` // 是否已配置
	Valid      bool   `json:"valid"`      // 是否有效
	ExpiresAt  string `json:"expiresAt"`  // 过期时间
	Message    string `json:"message"`    // 状态消息
}

type SetSMBConfigReq struct {
	Enabled  bool   `json:"enabled"`
	Host     string `json:"host,optional"`
	Share    string `json:"share,optional"`
	Username string `json:"username,optional"`
	Password string `json:"password,optional"`
}

type GetSMBConfigReq struct {
}

type GetSMBConfigResp struct {
	Enabled    bool   `json:"enabled"`
	Host       string `json:"host"`
	Share      string `json:"share"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	IsConnected bool  `json:"isConnected"`
}

type TestSMBConnectionReq struct {
	Host     string `json:"host"`
	Share    string `json:"share"`
	Username string `json:"username,optional"`
	Password string `json:"password,optional"`
}

// SMB 文件浏览相关类型
type SMBBrowseReq struct {
	Path string `json:"path,optional"`
}

type SMBFileItem struct {
	Name    string `json:"name"`
	Size    int64  `json:"size"`
	IsDir   bool   `json:"isDir"`
	ModTime string `json:"modTime"`
}

type SMBBrowseResp struct {
	Files      []SMBFileItem `json:"files"`
	CurrentPath string       `json:"currentPath"`
}

type SMBDownloadReq struct {
	RemotePath string `json:"remotePath"`
	LocalPath  string `json:"localPath,optional"`
}

type SMBDownloadResp struct {
	Success  bool   `json:"success"`
	Message  string `json:"message"`
	FilePath string `json:"filePath"`
}

type GetServerLogsReq struct {
	Type  string `json:"type,optional"`
	Lines int    `json:"lines,optional,default=200"`
}

type GetServerLogsResp struct {
	Logs []string `json:"logs"`
}

type CloudFile struct {
	FileID     string `json:"fileId"`
	FileName   string `json:"fileName"`
	FileSize   int64  `json:"fileSize"`
	IsDir      bool   `json:"isDir"`
	ParentID   string `json:"parentId"`
	UpdateTime string `json:"updateTime"`
	PickCode   string `json:"pickCode,omitempty"`
}

type GetCloudFilesReq struct {
	FolderID string `json:"folderId,optional,default=0"`
	FileType int    `json:"fileType,optional"`
}

type GetCloudFilesResp struct {
	Files      []CloudFile `json:"files"`
	CurrentID  string      `json:"currentId"`
	ParentID   string      `json:"parentId"`
}

type CreateFolderReq struct {
	ParentID   string `json:"parentId"`
	FolderName string `json:"folderName"`
}

type CreateFolderResp struct {
	FileID   string `json:"fileId"`
	FileName string `json:"fileName"`
}

type DeleteFileReq struct {
	FileIDs string `json:"fileIds"`
}

type RenameFileReq struct {
	FileID   string `json:"fileId"`
	NewName  string `json:"newName"`
}

type MoveFileReq struct {
	FileIDs    string `json:"fileIds"`
	TargetDir  string `json:"targetDir"`
}

type SetDefaultDownloadDirReq struct {
	FolderID   string `json:"folderId"`
	FolderName string `json:"folderName"`
}

type GetDefaultDownloadDirReq struct {
}

type GetDefaultDownloadDirResp struct {
	FolderID   string `json:"folderId"`
	FolderName string `json:"folderName"`
}
